// Fails when the two languages differ in keys or placeholders, or when an engine
// reason / app error code (codes.json, generated by Rust) has no translation.
import { readFileSync } from 'node:fs';

const load = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url), 'utf8'));
const en = load('../src/i18n/en.json');
const pt = load('../src/i18n/pt-PT.json');
const codes = load('../src/i18n/codes.json');

const placeholders = (s) => [...s.matchAll(/\{(\w+)\}/g)].map((m) => m[1]).sort().join(',');
const problems = [];
for (const k of Object.keys(en)) if (!(k in pt)) problems.push(`pt-PT is missing "${k}"`);
for (const k of Object.keys(pt)) if (!(k in en)) problems.push(`en is missing "${k}"`);
for (const k of Object.keys(en)) {
  if (k in pt && placeholders(en[k]) !== placeholders(pt[k])) problems.push(`placeholders differ in "${k}"`);
}
for (const c of codes.reason) if (!(`reason.${c}` in en)) problems.push(`no text for engine code "reason.${c}"`);
for (const c of codes.error) if (!(`error.${c}` in en)) problems.push(`no text for app error "error.${c}"`);

if (problems.length > 0) {
  console.error(problems.join('\n'));
  process.exit(1);
}
console.log(`i18n ok: ${Object.keys(en).length} keys in en and pt-PT`);
